### ekf config file ###
ekf_filter_node:
    ros__parameters:
        debug: true
        frequency: 50.0
        two_d_mode: true
        publish_acceleration: false
        publish_tf: true
        map_frame: map              
        odom_frame: odom           
        base_link_frame: base_footprint
        world_frame: odom          #局部融合

        odom0: /odom
        odom0_config: [true,  true,  false,
                       false, false, true,
                       false, false, false,
                       false, false, true,
                       false, false, false]

        imu0: /imu
        imu0_config: [false, false, false,
                      false, false, true,
                      false, false, false,
                      false, false, true,
                      false, false, false]